api_platform:
  title: Highload API
  version: 1.0.0
  mapping:
    paths:
      - '%kernel.project_dir%/src/UI/Controller'
  formats:
    json:
      mime_types:
        - application/json
  patch_formats:
    json:
      - application/merge-patch+json
  error_formats:
    json:
      mime_types:
        - application/json
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
