framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true
  serializer:
    enabled: true
  session:
    enabled: false
  cache:
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_URL)%'
  rate_limiter:
    login_request:
      policy: 'fixed_window'
      limit: '%env(int:LOGIN_RATE_LIMIT)%'
      interval: '1 minute'
      cache_pool: 'cache.app'
